name: Publish multi-arch Docker images

on:
    push:
        branches:
            - main

jobs:
    release:
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                base: [ 'giof71/mpd-base-image:mpd-0.22.6-bullseye-2022-02-12', 'giof71/mpd-base-image:mpd-0.21.5-buster-2022-02-12', 'giof71/mpd-base-image:mpd-0.21.20-ubuntu-focal-2022-02-12' ]
                
        steps:
        -
            name: Checkout
            uses: actions/checkout@v2
        -
            name: Set Release Tag
            run: |
                date=$(date '+%Y-%m-%d')
                base="$(cut -d ':' -f2 <<< '${{ matrix.base }}')"
                echo "base=${base}"
                base="$(cut -d '-' -f2 <<< '${base}')"
                base="$(cut -d '-' -f1 <<< '${base}')"
                mpd_version=""
                if [ "${base}" = "bullseye" ]; then \
                    base="bullseye";
                    mpd_version="mpd-0.22.6-"; \
                fi
                if [ "${base}" = "buster" ]; then \
                    base="buster";
                    mpd_version="mpd-0.21.5-"; \
                fi
                if [ "${base}" = "focal" ]; then \
                    base="ubuntu-focal"; \
                    mpd_version="mpd-0.21.20-"; \
                fi
                tags="${{secrets.DOCKER_USERNAME}}/mpd-alsa:${mpd_version}${base},${{secrets.DOCKER_USERNAME}}/mpd-alsa:${mpd_version}${base}-${date}"
                if [ "${base}" = "buster" ]; then \
                    echo "RELEASE_TAGS=${tags},${{secrets.DOCKER_USERNAME}}/mpd-alsa:${base},${{secrets.DOCKER_USERNAME}}/mpd-alsa:stable"; \
                elif [ "${base}" = "bullseye" ]; then \
                    echo "RELEASE_TAGS=${tags},${{secrets.DOCKER_USERNAME}}/mpd-alsa:${base},${{secrets.DOCKER_USERNAME}}/mpd-alsa:latest"; \
                elif [ "${base}" = "focal" ]; then \
                    echo "RELEASE_TAGS=${tags},${{secrets.DOCKER_USERNAME}}/mpd-alsa:${base}"; \
                else \
                    echo "RELEASE_TAGS=${tags}"; \
                fi \
                >> $GITHUB_ENV
        -
            name: Set up QEMU
            uses: docker/setup-qemu-action@v1
            with:
                platforms: all
        -
            name: Set up Docker Buildx
            id: buildx
            uses: docker/setup-buildx-action@v1
        -
            name: Login to DockerHub
            uses: docker/login-action@v1
            with:
                username: ${{ secrets.DOCKER_USERNAME }}
                password: ${{ secrets.DOCKER_PASSWORD }}
        -
            name: Build and push
            uses: docker/build-push-action@v2
            with:
                context: .
                build-args: |
                    BASE_IMAGE=${{ matrix.base }}
                platforms: linux/amd64,linux/arm/v7,linux/arm64/v8
                push: true
                tags: ${{ env.RELEASE_TAGS }}
