name: Publish multi-arch Docker images

on:
  push:
    tags:
      - "legacy/*"
      - "legacy-hotfix/*"

jobs:
  release:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        base: ["bullseye", "jammy"]

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Prepare for docker build
        run: |
          ref_type=${{ github.ref_type }}
          echo "REF_TYPE: ["$ref_type"]"

          ref_name=${{ github.ref_name }}
          echo "REF_NAME: ["$ref_name"]"

          ref=${{ github.ref }}
          echo "REF: ["$ref"]"

          distro_id=${{ matrix.base }}
          image_name=${{secrets.DOCKER_USERNAME}}/mpd-alsa

          declare -A base_image_from_matrix
          base_image_from_matrix[bookworm]=debian:bookworm-slim
          base_image_from_matrix[buster]=debian:buster-slim
          base_image_from_matrix[bullseye]=debian:bullseye-slim
          base_image_from_matrix[bionic]=ubuntu:bionic
          base_image_from_matrix[focal]=ubuntu:focal
          base_image_from_matrix[jammy]=ubuntu:jammy
          base_image_from_matrix[kinetic]=ubuntu:kinetic

          declare -A mpd_versions
          mpd_versions[buster]=0.21.5
          mpd_versions[bullseye]=0.22.6
          mpd_versions[bookworm]=0.23.9
          mpd_versions[bionic]=0.20.18
          mpd_versions[focal]=0.21.20
          mpd_versions[jammy]=0.23.5
          mpd_versions[kinetic]=0.23.9

          declare -A special_tags
          special_tags[bullseye]="${image_name}:stable,${image_name}:legacy-latest"
          special_tags[bookworm]="${image_name}:legacy-edge"
          special_tags[buster]="${image_name}:legacy,${image_name}:legacy-old-stable"
          special_tags[bionic]="${image_name}:legacy-ubuntu-old-lts"
          special_tags[focal]="${image_name}:legacy-ubuntu-previous-lts"
          special_tags[jammy]="${image_name}:legacy-ubuntu-current-lts"
          special_tags[kinetic]="${image_name}:legacy-ubuntu-current"

          base_image=${base_image_from_matrix[${{ matrix.base }}]}
          #mpd_version=${mpd_versions[${{ matrix.base }}]}
          # compiled version is 0.23.12
          mpd_version=0.23.12

          tags=""
          if [ "${ref_type}" = "tag" ]; then
            echo "tag mode";
            echo "tag is ["${ref_name}"]";

            tag_type=$(echo ${ref_name} | cut -d '/' -f 1)
            tag_name=$(echo ${ref_name} | cut -d '/' -f 2) 

            if [ "${tag_type}" = "legacy" ]; then
              echo "release tag";
              echo "Building now: ["$distro_id"]";
              tags="${tags},$image_name:legacy-${distro_id}";
              tags="${tags},$image_name:legacy-${distro_id}-${mpd_version}"
              tags="$tags,$image_name:legacy-${distro_id}-${mpd_version}-${tag_name}"              
              select_special_tags=${special_tags["${distro_id}"]};
              if [[ -n "${select_special_tags}" ]]; then
                echo "Found special tags for ["${distro_id}"]=["${select_special_tags}"]";
                tags="$tags,${select_special_tags}";
              else
                echo "No special tag found for ["${distro_id}"]";
              fi
            elif [ "${tag_type}" = "legacy-hotfix" ]; then
              echo "feature tag";
              tags="${image_name}:legacy-hotfix-${tag_name}-${distro_id}-${mpd_version}";
            fi
          fi
          echo "Building tags: ["${tags}"]"
          echo "RELEASE_TAGS=${tags}" >> $GITHUB_ENV
          echo "BASE_IMAGE=${base_image}" >> $GITHUB_ENV

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: all

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          build-args: |
            BASE_IMAGE=${{ env.BASE_IMAGE }}
          platforms: linux/amd64,linux/arm/v7,linux/arm64/v8
          push: true
          tags: ${{ env.RELEASE_TAGS }}
